"""One-time chat title generation.

Replaces the previous "first N characters of the user's message" heuristic
(chat_store.py's _derive_title, kept as a fallback) with a short, actually
descriptive title generated by a single lightweight model-orch call --
same idea as Claude Code's own auto-titled conversations.

Called exactly once per chat, right after its first turn finishes (see
api/chat.py's persist_active_chat) -- never regenerated after that, even if
the conversation wanders somewhere completely different. A title is a
nice-to-have, not something worth spending retries or context budget on, so
any failure here just falls back to the existing heuristic rather than
holding up the turn.
"""

from __future__ import annotations

import logging

from samixa_code.llm.client import ModelOrchClient, ModelOrchError
from samixa_code.llm.types import ChatMessage

logger = logging.getLogger(__name__)

MAX_TITLE_CHARS = 60
# Small on purpose -- a title is a handful of words, and this rides on the
# same 16k-token budget as everything else even though the prompt itself is tiny.
TITLE_MAX_TOKENS = 24

_TITLE_SYSTEM_PROMPT = (
    "Reply with ONLY a short, specific chat title (3-6 words) summarizing what the "
    "user below is asking for. No quotes, no trailing punctuation, no preamble -- "
    "just the title itself."
)


async def generate_chat_title(llm: ModelOrchClient, first_user_message: str) -> str | None:
    """Best-effort: returns None on any failure so the caller can fall back
    to the heuristic in chat_store.py instead of leaving the chat untitled."""
    try:
        response = await llm.chat(
            [
                ChatMessage(role="system", content=_TITLE_SYSTEM_PROMPT),
                # Capped defensively -- this is meant to be a quick summary
                # call, not another place the token budget has to be managed.
                ChatMessage(role="user", content=first_user_message[:2000]),
            ],
            tools=None,
            max_tokens=TITLE_MAX_TOKENS,
        )
    except ModelOrchError as exc:
        logger.warning("chat title generation failed, falling back to heuristic: %s", exc)
        return None

    title = response.text.strip().strip("\"'").strip()
    if not title:
        return None
    if len(title) > MAX_TITLE_CHARS:
        title = title[:MAX_TITLE_CHARS].rstrip() + "…"
    return title
